version: '3.8'

#
# ATLAS
#

services:

  #  adminer:
  #    image: adminer
  #    container_name: adminer
  #    networks:
  #      - outside
  #      - authelia_db
  #      - nextcloud_db
  #      - teamspeak_db
  #    ports:
  #      - "8080:8080"
  #    restart: always

  authelia:
    image: authelia/authelia:${AUTHELIA}
    container_name: authelia
    depends_on:
      - authelia_db
    networks:
      - auth
      - authelia_db
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD_FILE=/run/secrets/ldap_auth
      - AUTHELIA_JWT_SECRET_FILE=/run/secrets/authelia_jwt
      - AUTHELIA_STORAGE_MYSQL_PASSWORD_FILE=/run/secrets/authelia_db
      - AUTHELIA_SESSION_SECRET_FILE=/run/secrets/authelia_session
    volumes:
      - ./volumes/authelia:/config:z
      - ./configs/authelia/configuration.yml:/config/configuration.yml:z
    secrets:
      - authelia_jwt
      - authelia_session
      - ldap_auth
      - authelia_db
    restart: always

  authelia_db:
    image: linuxserver/mariadb:${MARIADB}
    container_name: authelia_db
    networks:
      - authelia_db
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - MYSQL_DATABASE=authelia
      - MYSQL_USER=authelia
      - FILE__MYSQL_PASSWORD=/run/secrets/authelia_db
      - FILE__MYSQL_ROOT_PASSWORD=/run/secrets/authelia_db
    volumes:
      - ./volumes/authelia_db:/config:z
    secrets:
      - authelia_db
    restart: always

  inadyn:
    image: ctor/inadyn:${INADYN}
    container_name: inadyn
    build: ./images/inadyn
    networks:
      - outside
    environment:
      - TZ=${TZ}
    volumes:
      - ./volumes/inadyn:/config:z
      - ./configs/inadyn/inadyn.conf:/config/inadyn.conf:z
    restart: always

  ldap:
    image: ctor/ldap:${LDAP}
    container_name: ldap
    build: ./images/ldap
    networks:
      - auth
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - LDAP_DOMAIN=${LDAP_DOMAIN}
      - LDAP_ROOT=root
      - LDAP_BIND_USER=auth
      - LDAP_CERTS=/config/certs/live/<domain>
      - FILE__LDAP_CONFIG_PASSWORD=/run/secrets/ldap_db
      - FILE__LDAP_ROOT_PASSWORD=/run/secrets/ldap_db
      - FILE__LDAP_BIND_PASSWORD=/run/secrets/ldap_auth
    volumes:
      - ./volumes/ldap:/config:z
      - ./configs/ldap:/config/initdb.d:ro,z
      - ./volumes/swag/etc/letsencrypt:/config/certs:ro,z
    secrets:
      - ldap_auth
      - ldap_db
    ulimits:
      nofile: 1024
    restart: always

  nextcloud:
    image: linuxserver/nextcloud:${NEXTCLOUD}
    container_name: nextcloud
    depends_on:
      - ldap
      - nextcloud_db
    networks:
      - auth
      - mail
      - nextcloud_db
      - proxy
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=${UMASK}
    volumes:
      - ./volumes/nextcloud:/config:z
      - ${VOLUME_NEXTCLOUD}:/data:z
      - ${VOLUME_MEDIA}:/media:z
      - ${VOLUME_POOL}:/pool:z
      - ${VOLUME_SYNC}:/sync:z
    restart: always

  nextcloud_db:
    image: linuxserver/mariadb:${MARIADB}
    container_name: nextcloud_db
    networks:
      - nextcloud_db
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - FILE__MYSQL_PASSWORD=/run/secrets/nextcloud_db
      - FILE__MYSQL_ROOT_PASSWORD=/run/secrets/nextcloud_db
    volumes:
      - ./volumes/nextcloud_db:/config:z
    secrets:
      - nextcloud_db
    restart: always

  plex:
    image: linuxserver/plex:${PLEX}
    container_name: plex
    networks:
      - proxy
    #ports:
    # - "32400:32400/tcp"
    # - "3005:3005/tcp"
    # - "8324:8324/tcp"
    # - "32469:32469/tcp"
    # - "1900:1900/udp"
    # - "32410:32410/udp"
    # - "32412:32412/udp"
    # - "32413:32413/udp"
    # - "32414:32414/udp"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=${UMASK}
      - VERSION=docker
    # - PLEX_CLAIM=
    deploy:
      resources:
        limits:
          memory: 8G
    volumes:
      - ./volumes/plex:/config:z
      - ${VOLUME_MEDIA}:/data:z
    restart: always

  protonmail-bridge:
    image: ctor/protonmail-bridge:${PROTONMAIL_BRIDGE}
    container_name: protonmail-bridge
    build: ./images/protonmail-bridge
    networks:
      - outside
      - mail
    ports:
      - "25:1025"
      - "143:1143"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Europe/Zurich
      - PROTONMAIL_ADDRESS=<email>
      - PROTONMAIL_PASSWORD=<password>
      - PROTONMAIL_PASSWORD_MAILBOX=<mailbox-password>
    volumes:
      - ./volumes/protonmail-bridge:/config:z
    restart: always

  restic_data:
    image: ctor/restic:${RESTIC}
    container_name: restic_data
    build: ./images/restic
    networks:
      - outside
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Europe/Zurich
      - RESTIC_REPOSITORY=<empty>
      - RESTIC_SCHEDULE=30 4 * * *
      - RESTIC_BACKUP_TAGS=data
      - RESTIC_FORGET_ARGS=--prune --keep-daily 7 --keep-weekly 4 --keep-monthly 3 --keep-yearly 1
      - FILE__RESTIC_PASSWORD=/run/secrets/restic_data
      - FILE__B2_ACCOUNT_ID=/run/secrets/backblaze_id
      - FILE__B2_ACCOUNT_KEY=/run/secrets/backblaze_key
    volumes:
      - ./volumes/restic_data:/config:z
      # Backup sources.
      - /mnt/data/backup:/data/backup:ro,z
      - /mnt/data/media:/data/media:ro,z
      - /mnt/data/nextcloud:/data/nextcloud:ro,z
      - /mnt/data/pool:/data/pool:ro,z
      - /mnt/data/syncthing:/data/syncthing:ro,z
    secrets:
      - backblaze_id
      - backblaze_key
      - restic_data
    restart: always

  restic_volumes:
    image: ctor/restic:${RESTIC}
    container_name: restic_volumes
    build: ./images/restic
    networks:
      - outside
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Europe/Zurich
      - RESTIC_REPOSITORY=<empty>
      - RESTIC_SCHEDULE=30 3 * * *
      - RESTIC_BACKUP_TAGS=volumes
      - RESTIC_FORGET_ARGS=--prune --keep-daily 7 --keep-weekly 4 --keep-monthly 3 --keep-yearly 1
      - FILE__RESTIC_PASSWORD=/run/secrets/restic_volumes
      - FILE__B2_ACCOUNT_ID=/run/secrets/backblaze_id
      - FILE__B2_ACCOUNT_KEY=/run/secrets/backblaze_key
    volumes:
      - ./volumes/restic_volumes:/config:z
      # Backup sources.
      - ./volumes/authelia:/data/authelia:ro,z
      - ./volumes/authelia_db:/data/authelia_db:ro,z
      - ./volumes/ldap:/data/ldap:ro,z
      - ./volumes/nextcloud:/data/nextcloud:ro,z
      - ./volumes/nextcloud_db:/data/nextcloud_db:ro,z
      - ./volumes/swag:/data/swag:ro,z
      - ./volumes/syncthing:/data/syncthing:ro,z
      - ./volumes/teamspeak:/data/teamspeak:ro,z
      - ./volumes/teamspeak_db:/data/teamspeak_db:ro,z
    secrets:
      - backblaze_id
      - backblaze_key
      - restic_volumes
    restart: always

  swag:
    image: linuxserver/swag:${SWAG}
    container_name: swag
    depends_on:
      - nextcloud
      - plex
      - syncthing
    cap_add:
      - NET_ADMIN
    networks:
      - outside
      - auth
      - proxy
    ports:
      - "80:80"
      - "443:443"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - URL=<domain>
      - SUBDOMAINS=wildcard
      - VALIDATION=dns
      - DNSPLUGIN=cloudflare
      - FILE__MAXMINDDB_LICENSE_KEY=/run/secrets/maxmind
    #  - STAGING=true
    volumes:
      - ./volumes/swag:/config:z
      - ./configs/blog:/config/www:z
    secrets:
      - cloudflare
      - maxmind
    restart: always

  syncthing:
    image: linuxserver/syncthing:${SYNCTHING}
    container_name: syncthing
    networks:
      - outside
      - proxy
    ports:
      # - "8384:8384"
      - "22000:22000"
      - "21027:21027/udp"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=${UMASK}
    volumes:
      - ./volumes/syncthing:/config:z
      - ${VOLUME_SYNC}:/data1:z
    restart: always

  teamspeak:
    image: teamspeak:${TEAMSPEAK}
    container_name: teamspeak
    depends_on:
      - teamspeak_db
    networks:
      - outside
      - teamspeak_db
    ports:
      - "9987:9987/udp"
      - "10011:10011"
      - "30033:30033"
    environment:
      - TZ=${TZ}
      - TS3SERVER_DB_PLUGIN=ts3db_mariadb
      - TS3SERVER_DB_SQLCREATEPATH=create_mariadb
      - TS3SERVER_DB_HOST=teamspeak_db
      - TS3SERVER_DB_USER=teamspeak
      - TS3SERVER_DB_PASSWORD_FILE=/run/secrets/teamspeak_db
      - TS3SERVER_DB_NAME=teamspeak
      - TS3SERVER_DB_WAITUNTILREADY=30
      - TS3SERVER_LICENSE=accept
    volumes:
      - ./volumes/teamspeak:/var/ts3server:z
    secrets:
      - teamspeak_db
    restart: always

  teamspeak_db:
    image: linuxserver/mariadb:${MARIADB}
    container_name: teamspeak_db
    networks:
      - teamspeak_db
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - MYSQL_DATABASE=teamspeak
      - MYSQL_USER=teamspeak
      - FILE__MYSQL_PASSWORD=/run/secrets/teamspeak_db
      - FILE__MYSQL_ROOT_PASSWORD=/run/secrets/teamspeak_db
    volumes:
      - ./volumes/teamspeak_db:/config:z
    secrets:
      - teamspeak_db
    restart: always

  udpxy:
    image: ctor/udpxy:${UDPXY}
    container_name: udpxy
    build: ./images/udpxy
    network_mode: "host"
    environment:
      - TZ=${TZ}
    restart: always

networks:
  outside:
    name: outside
  auth:
  mail:
  proxy:
  authelia_db:
  nextcloud_db:
  teamspeak_db:

secrets:
  authelia_jwt:
    file: ./secrets/authelia_jwt
  authelia_session:
    file: ./secrets/authelia_session
  backblaze_id:
    file: ./secrets/backblaze_id
  backblaze_key:
    file: ./secrets/backblaze_key
  cloudflare:
    file: ./secrets/cloudflare
  maxmind:
    file: ./secrets/maxmind
  restic_data:
    file: ./secrets/restic_data
  restic_volumes:
    file: ./secrets/restic_volumes
  # Users
  ldap_auth:
    file: ./secrets/ldap_auth
  # Databases
  authelia_db:
    file: ./secrets/authelia_db
  ldap_db:
    file: ./secrets/ldap_db
  nextcloud_db:
    file: ./secrets/nextcloud_db
  teamspeak_db:
    file: ./secrets/teamspeak_db
