theme: auto

log:
  level: error

telemetry:
  metrics:
    enabled: true

# Add OIDC clients.
#identity_providers:
#  oidc:
#    clients:

authentication_backend:
  ldap:
    tls:
      skip_verify: true

    implementation: custom

    additional_groups_dn: ou=groups
    additional_users_dn: ou=people
    groups_filter: "(member={dn})"
    users_filter: "(&({username_attribute}={input})(objectClass=person))"

    display_name_attribute: displayName
    mail_attribute: mail
    group_name_attribute: cn
    username_attribute: uid

access_control:
  # Add rules.
#  rules:
#    - domain:
#        - domain.com
#      policy: bypass
