- name: alpine
  watch_repo: true
  notify_on: new
  max_tags: 10
  include_tags:
    - ^\d+\.\d+\.\d+
- name: haproxy
  watch_repo: true
  notify_on: new
  max_tags: 10
  include_tags:
    - ^\d+\.\d+\.\d+-alpine.*
- name: nginxinc/nginx-unprivileged:1.24.0-alpine-slim
  watch_repo: true
  notify_on: new
  max_tags: 10
  include_tags:
    - ^\d+\.\d+\.\d+-alpine-slim
