#!/usr/bin/with-contenv bash

set -e

[[ -f /config/restic/excludes ]] || s6-setuidgid abc cp /defaults/restic/excludes /config/restic/excludes
[[ -f /config/restic/options ]] || s6-setuidgid abc cp /defaults/restic/options /config/restic/options

[[ $(s6-setuidgid abc restic snapshots >>/dev/null 2>&1) ]] && exit 0

s6-setuidgid abc restic init >>/config/log/restic/restic.log 2>&1

echo "atlas :: restic :: initialized repository"
