#!/command/with-contenv bash

HOME=~abc
export HOME

rm -f faketty
mkfifo faketty

# Fake a terminal, so it does not quit because of EOF.
# shellcheck disable=SC2002
cat faketty | exec s6-setuidgid abc /app/proton-bridge --cli
