#!/command/with-contenv bash

# Fixes high memory usage.
ulimit -n 1024

# s6 v3 fix.
chown abc:abc /run/openldap

/usr/sbin/slapd \
    -u abc -g abc \
    -h "ldap:/// ldaps:///" \
    -F /config/databases/slapd.d \
    -d 0
