#!/command/with-contenv bash

[[ -f /config/databases/openldap-data/data.mdb ]] && exit 0

. /opt/util/file.sh
. /opt/util/ldap.sh
. /opt/util/placeholder.sh
. /opt/util/string.sh

DATABASE_INIT="/tmp/database.ldif"

merge_files "/defaults/openldap/database/*.ldif" "${DATABASE_INIT}"

BIND_PASSWORD="$(create_password_hash "${LDAP_BIND_PASSWORD}")"

# shellcheck disable=SC2046
LDAP_DOMAIN="$(join_by "," $(prepend_each "dc=" $(split "${DOMAIN}")))"
ORGANIZATION="$(get_organization "${LDAP_DOMAIN}")"

replace_placeholder LDAP_BIND_USER "${LDAP_BIND_USER}" "${DATABASE_INIT}"
replace_placeholder LDAP_BIND_PASSWORD "${BIND_PASSWORD}" "${DATABASE_INIT}"
replace_placeholder LDAP_DOMAIN "${LDAP_DOMAIN}" "${DATABASE_INIT}"
replace_placeholder LDAP_ROOT "${LDAP_ROOT}" "${DATABASE_INIT}"
replace_placeholder ORGANIZATION "${ORGANIZATION}" "${DATABASE_INIT}"

s6-setuidgid abc slapadd -n 1 -F /config/databases/slapd.d -l "${DATABASE_INIT}"

rm "${DATABASE_INIT}"

echo "atlas :: ldap :: created user database"

[[ ! -d /config/initdb.d ]] && exit 0

CUSTOM_INIT="/tmp/custom.ldif"

merge_files "/config/initdb.d/*.ldif" "${CUSTOM_INIT}"

slapd -h "ldapi://%2Frun%2Fopenldap%2Fldapi" -F /config/databases/slapd.d -u abc -g abc &
while [[ ! -e /run/openldap/slapd.pid ]]; do sleep 0.1; done

ldapadd -c -Y EXTERNAL -Q -H "ldapi://%2Frun%2Fopenldap%2Fldapi" -f "${CUSTOM_INIT}" >/dev/null 2>&1

PID="$(cat /run/openldap/slapd.pid)"
kill -SIGTERM "${PID}"
while [[ -e "/proc/${PID}" ]]; do sleep 0.1; done

rm "${CUSTOM_INIT}"

echo "atlas :: ldap :: applied custom entries"
