#!/usr/bin/with-contenv bash

[[ -e /config/.installed ]] && exit 0

CONFIG=/config/databases/slapd.d

if [ -d /config/initdb.d ]; then

  slapd -h "ldapi://%2Frun%2Fopenldap%2Fldapi" -F "$CONFIG" -u abc -g abc &
  while [ ! -e /run/openldap/slapd.pid ]; do sleep 0.1; done

  for file in /config/initdb.d/*.ldif; do
    [ -e "$file" ] || continue
    ldapadd -c -Y EXTERNAL -Q -H ldapi://%2Frun%2Fopenldap%2Fldapi -f "$file" >/dev/null 2>&1
  done

  PID=$(cat /run/openldap/slapd.pid)
  kill -SIGTERM "$PID"
  while [ -e "/proc/$PID" ]; do sleep 0.1; done
fi

touch /config/.installed
