#!/usr/bin/with-contenv bash

[[ -d /config/.gnupg ]] && exit 0

s6-setuidgid abc /usr/bin/gpg --quiet --generate-key --batch <<EOF
  %no-protection
  Key-Type: RSA
  Key-Length: 4096
  Name-Real: pass-key
  Expire-Date: 0
  %commit
EOF
